on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect-directory-changes:
    name: Detect Directory Changes Job
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.detect.outputs.changed }}
    steps:
      - name: DDC Checkout Step
        uses: actions/checkout@v2

      - name: Detect Directory Changes
        id: detect
        uses: tchupp/actions-detect-directory-changes@v0.1.8

  build:
    name: Build sub-projects Job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJSON(needs.detect-directory-changes.outputs.changed) }}
    steps:
      - name: Build Checkout Step
        uses: actions/checkout@v2

      - name: Build ${{ matrix.project }}
        working-directory: ./${{ matrix.project }}
        run: echo Directory Changed!
