name: Test tj-actions/changed-file

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3

      - name: Get files that changed
        id: changed-files
        uses: tj-actions/changed-files@v36

      - name: Show files that changed
        run: |
          echo '${{ toJSON(steps.changed-files.outputs.all_changed_files) }}'
        shell: bash

      - name: Get example files that changed
        id: changed-example-files
        uses: tj-actions/changed-files@v36
        with:
          files: examples

      - name: Show example files that changed
        run: |
          echo '${{ toJSON(steps.changed-example-files.outputs.all_changed_files) }}'
        shell: bash

      - name: Get example subdirectories that changed
        id: changed-example-dirs
        uses: tj-actions/changed-files@v36
        with:
          files: examples/*
          dir_names: "true"

      - name: Show example subdirectories that changed
        run: |
          echo '${{ toJSON(steps.changed-example-dirs.outputs.all_changed_files) }}'
        shell: bash

      - name: Run action for example subdirectories that changed if no common changes
        if: "steps.changed-example-dirs.outputs.any_changed == 'true' && !contains(steps.changed-example-dirs.outputs.all_changed_files, 'examples/common')"
        run: |
          for dir in ${{steps.changed-example-dirs.outputs.
          root_dir=$(pwd)
          all_changed_files}}; do
              echo
              echo Moving to $dir
              ls $dir
              cd $root_dir
          done
        shell: bash

      - name: Run action on common change
        if: "contains(steps.changed-example-dirs.outputs.all_changed_files, 'examples/common')"
        run: |
          echo Simulate action on common change
        shell: bash
